// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/FatwahFir/golearn/app"
	"github.com/FatwahFir/golearn/controllers/category"
	"github.com/FatwahFir/golearn/middleware"
	"github.com/FatwahFir/golearn/repository/category"
	"github.com/FatwahFir/golearn/services/category"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"net/http"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializeServer() *http.Server {
	categoryRepositoryImpl := categoryRepository.NewCategoryRepository()
	db := app.NewDb()
	v := ProvideValidatorOptions()
	validate := validator.New(v...)
	categoryServiceImpl := categoryService.NewCategoryService(categoryRepositoryImpl, db, validate)
	categoryControllerImpl := categoryController.NewCategoryController(categoryServiceImpl)
	router := app.NewRouter(categoryControllerImpl)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var categorySet = wire.NewSet(categoryRepository.NewCategoryRepository, wire.Bind(new(categoryRepository.CategoryRepository), new(*categoryRepository.CategoryRepositoryImpl)), categoryService.NewCategoryService, wire.Bind(new(categoryService.CategoryService), new(*categoryService.CategoryServiceImpl)), categoryController.NewCategoryController, wire.Bind(new(categoryController.CategoryController), new(*categoryController.CategoryControllerImpl)))

func ProvideValidatorOptions() []validator.Option {
	return []validator.Option{}
}
